name: stretchers
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4
  - asttokens=3.0.0
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2025.10.5
  - cctools_osx-arm64=1010.6
  - clang=18.1.8
  - clang-18=18.1.8
  - clang_impl_osx-arm64=18.1.8
  - clang_osx-arm64=18.1.8
  - clangxx=18.1.8
  - clangxx_impl_osx-arm64=18.1.8
  - clangxx_osx-arm64=18.1.8
  - comm=0.2.3
  - compiler-rt=18.1.8
  - compiler-rt_osx-arm64=18.1.8
  - cpython=3.9.21
  - debugpy=1.8.16
  - decorator=5.2.1
  - eigen=3.4.0
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - fenics=2019.1.0
  - fenics-dijitso=2019.1.0
  - fenics-dolfin=2019.1.0
  - fenics-ffc=2019.1.0
  - fenics-fiat=2019.1.0
  - fenics-libdolfin=2019.1.0
  - fenics-ufl=2019.1.0
  - fftw=3.3.10
  - gmp=6.3.0
  - gmpy2=2.1.5
  - hdf5=1.14.3
  - hypre=2.32.0
  - icu=75.1
  - importlib-metadata=8.7.0
  - ipykernel=6.30.1
  - ipython=8.18.1
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - krb5=1.21.3
  - ld64_osx-arm64=951.9
  - libaec=1.1.3
  - libamd=3.3.3
  - libblas=3.9.0
  - libboost=1.86.0
  - libboost-headers=1.87.0
  - libbtf=2.3.2
  - libcamd=3.3.3
  - libcblas=3.9.0
  - libccolamd=3.3.4
  - libcholmod=5.3.0
  - libclang-cpp18.1=18.1.8
  - libcolamd=3.3.4
  - libcurl=8.12.1
  - libcxsparse=4.4.1
  - libcxx=19.1.7
  - libcxx-devel=18.1.8
  - libedit=3.1.20250104
  - libev=4.33
  - libfabric=2.0.0
  - libfabric1=2.0.0
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libglib=2.82.2
  - libhwloc=2.11.2
  - libiconv=1.18
  - libintl=0.23.1
  - libklu=2.3.5
  - liblapack=3.9.0
  - libldl=3.3.2
  - libllvm18=18.1.8
  - liblzma=5.6.4
  - libnghttp2=1.64.0
  - libopenblas=0.3.29
  - libparu=1.0.0
  - libptscotch=7.0.6
  - librbio=4.3.4
  - libscotch=7.0.6
  - libsodium=1.0.20
  - libspex=3.2.1
  - libspqr=4.3.4
  - libsqlite=3.49.1
  - libssh2=1.11.1
  - libsuitesparseconfig=7.8.3
  - libumfpack=6.3.5
  - libxml2=2.13.6
  - libzlib=1.3.1
  - llvm-openmp=19.1.7
  - llvm-tools=18.1.8
  - llvm-tools-18=18.1.8
  - matplotlib-inline=0.1.7
  - metis=5.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpi=1.0.1
  - mpi4py=4.0.3
  - mpich=4.3.0
  - mpmath=1.3.0
  - mumps-include=5.7.3
  - mumps-mpi=5.7.3
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - numpy=2.0.2
  - openssl=3.5.4
  - parmetis=4.0.3
  - parso=0.8.4
  - pcre2=10.44
  - petsc=3.22.3
  - petsc4py=3.22.3
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.0.1
  - pkg-config=0.29.2
  - pkgconfig=1.5.5
  - prompt-toolkit=3.0.51
  - psutil=7.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pybind11=2.13.6
  - pybind11-global=2.13.6
  - pygments=2.19.2
  - python=3.9.21
  - python-dateutil=2.9.0.post0
  - python_abi=3.9
  - pyzmq=27.0.2
  - readline=8.2
  - scalapack=2.2.0
  - setuptools=75.8.0
  - sigtool=0.1.3
  - six=1.17.0
  - slepc=3.22.2
  - slepc4py=3.22.2
  - stack_data=0.6.3
  - suitesparse=7.8.3
  - superlu=7.0.0
  - superlu_dist=9.1.0
  - tapi=1300.6.5
  - tk=8.6.13
  - tornado=6.5.2
  - traitlets=5.14.3
  - typing_extensions=4.14.1
  - tzdata=2025a
  - wcwidth=0.2.13
  - wheel=0.45.1
  - yaml=0.2.5
  - zeromq=4.3.5
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - absl-py==2.3.1
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - contourpy==1.3.0
      - cycler==0.12.1
      - einops==0.8.1
      - filelock==3.17.0
      - fonttools==4.56.0
      - fsspec==2025.2.0
      - grpcio==1.76.0
      - idna==3.10
      - imageio==2.37.0
      - importlib-resources==6.5.2
      - jinja2==3.1.5
      - kiwisolver==1.4.7
      - kornia==0.8.0
      - kornia-rs==0.1.8
      - lazy-loader==0.4
      - markdown==3.9
      - markupsafe==3.0.2
      - matplotlib==3.9.4
      - networkx==3.2.1
      - opencv-python==4.11.0.86
      - packaging==24.2
      - pillow==11.1.0
      - platformdirs==4.3.6
      - pooch==1.8.2
      - protobuf==6.33.1
      - pyparsing==3.2.1
      - pyvista==0.44.2
      - requests==2.32.3
      - scikit-image==0.24.0
      - scipy==1.13.1
      - scooby==0.10.0
      - sympy==1.13.1
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tifffile==2024.8.30
      - torch==2.6.0
      - torchvision==0.21.0
      - typing-extensions==4.12.2
      - urllib3==2.3.0
      - vtk==9.3.1
      - werkzeug==3.1.3
      - zipp==3.21.0
